version: '3'

services:
  postgres:
    build: ./database/postgres
    restart: always
    ports:
      - '5432:5432'
    env_file:
      - .env
    volumes:
      - ./database/data/postgres:/var/lib/postgresql/data
  redis:
    image: redis
    restart: always
    ports:
      - '6379:6379'
    command: >
      --requirepass ${REDIS_PASSWORD}
    volumes:
      - ./database/data/redis/redis.conf:/usr/local/etc/redis/redis.conf
